apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
spec:
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
      - name: karsajobs
        image: luthfi247/karsajobs:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: http://$(MONGO_SERVICE_HOST):(MONGO_SERVICE_PORT)
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME